#!/usr/bin/perl  -w

# This file is modified from sofa-pbrpc:
# https://github.com/baidu/sofa-pbrpc/blob/master/src/sofa/pbrpc/closure_gen.pl
# this perl script is used to generate Closure

$kPreMaxArgs = 10;
$kMaxArgs = 10;
sub PrintHead
{
    print "// Copyright (c) 2025-present\n\n";
    print "#pragma once\n";
    print "\n/////////////////////////////////////////////////////\n";
    print "// DO NOT EDIT!!!\n";
    print "// This header file is auto generated by perl script\n";
    print "/////////////////////////////////////////////////////\n\n";
    print "// GLOBAL_NOLINT(whitespace/line_length)\n";
    print "// GLOBAL_NOLINT(runtime/explicit)\n\n";
}

sub PrintClosure
{
    $kTotalArgs = $kPreMaxArgs + $kMaxArgs;
    print "template <\n    typename R";
    for($i = 1; $i <= $kTotalArgs; $i++)
    {
        print ",\n    typename Arg$i = void";
    }
    print "\n>\n\n";
    print "class Closure {\n";
    print "public:\n";
    print "    Closure() {}\n";
    print "    virtual ~Closure() {}\n\n";
    print "    virtual R Run(\n";
    for($i = 1; $i <= $kTotalArgs; $i++)
    {
        print "        Arg$i arg$i";
        if($i != $kTotalArgs)
        {
            print ",\n";
        }
    }
    print ") = 0;\n";
    print "    virtual bool IsSelfDelete() const = 0;\n";
    print "};\n\n";

    for($i = 0; $i < $kTotalArgs; $i++)
    {
        print "\n// for $i argument(s)\n";
        print "template <typename R";
        for($j = 1; $j <= $i; ++$j)
        {
            print ", typename Arg$j";
        }
        print ">\n";
        print "class Closure<R";
        for($j = 1; $j <= $i; ++$j)
        {
            print ", Arg$j";
        }
        print "> {\npublic:\n";
        print "    Closure() {}\n";
        print "    virtual ~Closure() {}\n\n";
        print "    virtual R Run(";
        for($j = 1; $j <= $i; ++$j)
        {
            print "Arg$j arg$j";
            if($j != $i)
            {
                print ", ";
            }
        }
        print ") = 0;\n";
        print "    virtual bool IsSelfDelete() const = 0;\n";
        print "};\n";
    }
}

sub PrintReturnValueHolder
{
    print "\n\n";
    print "template <typename R>\nclass ReturnValueHolder {\npublic:\n";
    print "    ReturnValueHolder(const R& value) : value_(value) {}\n";
    print "    const R& Value() const { return value_; }\n\n";
    print "private:\n    R value_;\n};\n\n";

    print "template <>\nclass ReturnValueHolder<void> {\npublic:\n";
    print "    void Value() const {}\n";
    print "};\n\n";
}

sub PrintCallHelper
{
    my($type,$is_void) = @_;
    if($type eq "cm")
    {
        $CallerName = "MethodCallHelper";
    }
    else
    {
        $CallerName = "FunctionCallHelper";
    }

    if($is_void)
    {
        print "template <>\nstruct ${CallerName}<void> {\n"
    }
    else
    {
        print "template <typename R>\nstruct ${CallerName} {\n";
    }
    for($i = 0; $i <= $kTotalArgs; ++$i)
    {
        if($i == 0 and $type eq "func")
        {
            print "";
        }
        else
        {
            if($i != 0)
            {
                print "\n";
            }
            print "    template <";
            if($type eq "cm")
            {
                print "typename Class";
                if($i > 0)
                {
                    print ", ";
                }
            }
            for($j = 1; $j <= $i; ++$j)
            {
                print "typename Arg$j";
                print ", " if($j != $i);
            }
            print ">\n";
        }
        print "    static ReturnValueHolder<";
        if($is_void)
        {
            print "void> Call(";
        }
        else
        {
            print "R> Call(";
        }
        if($type eq "cm")
        {
            print "Class *object, ";
        }
        if($is_void)
        {
            print "void ";
        }
        else
        {
            print "R ";
        }
        if($type eq "func")
        {
            print "(*function)(";
        }
        else
        {
            print "(Class::*method)(";
        }
        for($j = 1; $j <= $i; ++$j)
        {
            print "Arg$j arg$j";
            print ", " if($j != $i);
        }
        print ")";
        print ", " if($i > 0);
        for($j = 1; $j <= $i; ++$j)
        {
            print "Arg$j arg$j";
            print ", " if($j != $i);
        }
        print ") {\n";
        if($is_void)
        {
            if($type eq "func")
            {
                print "        function(";
            }
            else
            {
                print "        (object->*method)("
            }
        }
        else
        {
            if($type eq "func")
            {
                print "        ReturnValueHolder<R> result = function(";
            }
            else
            {
                print "        ReturnValueHolder<R> result = (object->*method)(";
            }
        }
        for($j = 1; $j <= $i; ++$j)
        {
            print "arg$j";
            print ", " if($j != $i);
        }

        print ");\n";
        if($is_void)
        {
            print "        return ReturnValueHolder<void>();\n";
        }
        else
        {
            print "        return result;\n";
        }
        print "    }\n"
    }
    print "};\n\n"
}

sub PrintClosure_Arg_Bind
{
    my($type) = @_;
    print "////////////////////////////////////////////////////\n";
    if($type eq "cm")
    {
        print "//////////// class method closures /////////////////\n";
    }
    else
    {
        print "//////////// nomal function closures ////////////////////\n";
    }
    print "////////////////////////////////////////////////////\n\n";

    for($i = 0; $i <= $kMaxArgs; ++$i)
    {
        for($j = 0; $j <= $kPreMaxArgs; $j++)
        {
            print "template<typename R";
            print ", typename Class" if($type eq "cm");
            for($k = 1; $k <= $j; $k++)
            {
                print ", typename PreArg$k";
            }
            for($k = 1; $k <= $i; $k++)
            {
                print ", typename Arg$k";
            }
            print ">\n";
            $ClassName = "MethodClosure_Arg${i}_Bind${j}" if($type eq "cm");
            $ClassName = "FunctionClosure_Arg${i}_Bind${j}" if($type eq "func");
            print "class ${ClassName} : public Closure<R";
            for($k = 1; $k <= $i; $k++)
            {
                print ", Arg$k";
            }
            print "> {\npublic:\n";
            if($type eq "cm")
            {
                $typedefName = "    typedef R (Class::*MethodType)(";
            }
            if($type eq "func")
            {
                $typedefName = "    typedef R (*FunctionType)(";
            }
            print $typedefName;
            $has_stuff = 0;
            for($k = 1; $k <= $j; $k++)
            {
                print ", " if($has_stuff);
                print "PreArg$k";
                $has_stuff = 1;
            }
            for($k = 1; $k <= $i; $k++)
            {
                print ", " if($has_stuff);
                print "Arg$k";
                $has_stuff = 1;
            }
            print ");\n";
            print "    $ClassName(";
            if($type eq "cm")
            {
                print "Class *object, MethodType method";
            }
            if($type eq "func")
            {
                print "FunctionType function";
            }
            print ", bool self_deleting";
            for($k = 1; $k <= $j; $k++)
            {
                print ", PreArg$k pa$k";
            }
            print ") : ";
            if($type eq "cm")
            {
                print "object_(object), method_(method), self_deleting_(self_deleting)";
            }
            if($type eq "func")
            {
                print "function_(function), self_deleting_(self_deleting)";
            }
            for($k = 1; $k <= $j; $k++)
            {
                print ", pa${k}_(pa${k})";
            }
            print " {}\n";
            print "    virtual ~${ClassName}() {}\n\n";
            print "    virtual R Run(";
            $has_stuff = 0;
            for($k = 1; $k <= $i; $k++)
            {
                print ", " if($has_stuff);
                print "Arg${k} arg${k}";
                $has_stuff = 1;
            }
            print ") {\n";
            print "        bool needs_delete = self_deleting_;\n";
            print "        ReturnValueHolder<R> res = ";
            if($type eq "cm")
            {
                print "Method";
            }
            if($type eq "func")
            {
                print "Function";
            }
            print "CallHelper<R>::Call(";
            if($type eq "cm")
            {
                print "object_, method_";
            }
            if($type eq "func")
            {
                print "function_";
            }
            for($k = 1; $k <= $j; $k++)
            {
                print ", pa$k\_";
            }
            for($k = 1; $k <= $i; $k++)
            {
                print ", arg$k";
            }
            print ");\n";
            print "        if (needs_delete) delete this;\n";
            print "        return res.Value();\n";
            print "    }\n";
            print "    bool IsSelfDelete() const { return self_deleting_; }\n\n";
            print "private:\n";
            if($type eq "cm")
            {
                print "    Class* object_;\n    MethodType method_;\n";
            }
            if($type eq "func")
            {
                print "    FunctionType function_;\n";
            }
            print "    bool self_deleting_;\n";
            for($k = 1; $k <= $j; $k++)
            {
                print "    PreArg${k} pa${k}_;\n";
            }
            print "};\n\n";
        }
    }
}

sub PrintNewClosure
{
    my ($type, $is_permanent) = @_;
    print "////////////////////////////////////////////////////\n";
    print "//////// Closure create helper functions ///////////\n";
    print "////////////////////////////////////////////////////\n";
    if($type eq "cm")
    {
        print "//////////// for class method //////////////////////\n\n";
    }
    else
    {
        print "//////////// for nomal function ////////////////////\n\n";
    }

    for ($i = 0; $i <= $kMaxArgs; $i++)
    {
        for ($j = 0; $j <= $kPreMaxArgs; $j++)
        {
            print "template<typename R";
            print ", typename Class" if($type eq "cm");
            for($k = 1; $k <= $j; $k++)
            {
                print ", typename PreArg$k";
            }
            for($k = 1; $k <= $i; $k++)
            {
                print ", typename Arg$k";
            }
            print ">\n";
            print "Closure<R";
            for($k = 1; $k <= $i; $k++)
            {
                print ", Arg$k";
            }
            print ">*";
            if($is_permanent)
            {
                print "NewPermanentClosure(";
            }
            else
            {
                print "NewClosure(";
            }
            if($type eq "cm")
            {
                print "Class *object, R (Class::*method)(";
            }
            else
            {
                print "R (*function)(";
            }
            $has_stuff = 0;
            for($k = 1; $k <= $j; $k++)
            {
                print ", " if($has_stuff);
                print "PreArg$k";
                $has_stuff = 1;
            }
            for($k = 1; $k <= $i; $k++)
            {
                print ", " if($has_stuff);
                print "Arg$k";
                $has_stuff = 1;
            }
            print ")";
            for($k = 1; $k <= $j; $k++)
            {
                print ", PreArg$k pa$k";
            }
            print ") {\n";

            if($type eq "cm")
            {
                print "    return new MethodClosure_Arg${i}_Bind${j}<R, Class";
            }
            else
            {
                print "    return new FunctionClosure_Arg${i}_Bind${j}<R";
            }
            for($k = 1; $k <= $j; $k++)
            {
                print ", PreArg$k";
            }
            for($k = 1; $k <= $i; $k++)
            {
                print ", Arg$k";
            }
            print ">(";
            if($type eq "cm")
            {
                print "object, method";
            }
            else
            {
                print "function";
            }
            if($is_permanent)
            {
                print ", false";
            }
            else
            {
                print ", true";
            }
            for($k = 1; $k <= $j; $k++)
            {
                print ", pa$k";
            }
            print ");\n}\n\n";
        }
    }
}

PrintHead();
PrintClosure();
PrintReturnValueHolder();
PrintCallHelper("cm", 0);
PrintCallHelper("cm", 1);
PrintCallHelper("func", 0);
PrintCallHelper("func", 1);
PrintClosure_Arg_Bind("cm");
PrintClosure_Arg_Bind("func");
PrintNewClosure("cm", 0);
PrintNewClosure("cm", 1);
PrintNewClosure("func", 0);
PrintNewClosure("func", 1);